language: r
sudo: false
cache: packages

before_install:
  - git config --global user.email "nicholas.j.clark1214@gmail.com"

script:
  - Rscript R/parasite.searches.R

after_success:
  - rm rtweet.rds
  - git add --all *
  - git commit -m"Weekly update"
  - git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
